# Generated by Django 3.0.7 on 2020-10-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201008_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.TextField(default='unknown', max_length=200),
        ),
    ]
