# Generated by Django 3.0.7 on 2020-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201008_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
